// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/baker-yuan/go-gateway/go-gateway-admin/internal/biz"
	"github.com/baker-yuan/go-gateway/go-gateway-admin/internal/conf"
	"github.com/baker-yuan/go-gateway/go-gateway-admin/internal/data"
	"github.com/baker-yuan/go-gateway/go-gateway-admin/internal/server"
	"github.com/baker-yuan/go-gateway/go-gateway-admin/internal/service"
	"github.com/baker-yuan/go-gateway/go-gateway-admin/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	httpRuleRepo := data.NewHttpRuleRepo(dataData, logger)
	httpRuleBiz := biz.NewHttpRuleBiz(httpRuleRepo, logger)
	httpRuleService := service.NewHttpRuleService(httpRuleBiz, logger)
	grpcServer := server.NewGRPCServer(confServer, httpRuleService, logger)
	httpServer := server.NewHTTPServer(confServer, httpRuleService, logger)
	registrar := registry.NewRegistrar()
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
