// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/baker-yuan/go-gateway/go-gateway-admin/internal/data/ent/httprule"
	"github.com/baker-yuan/go-gateway/go-gateway-admin/internal/data/ent/predicate"
)

// HttpRuleQuery is the builder for querying HttpRule entities.
type HttpRuleQuery struct {
	config
	ctx        *QueryContext
	order      []httprule.OrderOption
	inters     []Interceptor
	predicates []predicate.HttpRule
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HttpRuleQuery builder.
func (hrq *HttpRuleQuery) Where(ps ...predicate.HttpRule) *HttpRuleQuery {
	hrq.predicates = append(hrq.predicates, ps...)
	return hrq
}

// Limit the number of records to be returned by this query.
func (hrq *HttpRuleQuery) Limit(limit int) *HttpRuleQuery {
	hrq.ctx.Limit = &limit
	return hrq
}

// Offset to start from.
func (hrq *HttpRuleQuery) Offset(offset int) *HttpRuleQuery {
	hrq.ctx.Offset = &offset
	return hrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hrq *HttpRuleQuery) Unique(unique bool) *HttpRuleQuery {
	hrq.ctx.Unique = &unique
	return hrq
}

// Order specifies how the records should be ordered.
func (hrq *HttpRuleQuery) Order(o ...httprule.OrderOption) *HttpRuleQuery {
	hrq.order = append(hrq.order, o...)
	return hrq
}

// First returns the first HttpRule entity from the query.
// Returns a *NotFoundError when no HttpRule was found.
func (hrq *HttpRuleQuery) First(ctx context.Context) (*HttpRule, error) {
	nodes, err := hrq.Limit(1).All(setContextOp(ctx, hrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{httprule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hrq *HttpRuleQuery) FirstX(ctx context.Context) *HttpRule {
	node, err := hrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HttpRule ID from the query.
// Returns a *NotFoundError when no HttpRule ID was found.
func (hrq *HttpRuleQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = hrq.Limit(1).IDs(setContextOp(ctx, hrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{httprule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hrq *HttpRuleQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := hrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HttpRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HttpRule entity is found.
// Returns a *NotFoundError when no HttpRule entities are found.
func (hrq *HttpRuleQuery) Only(ctx context.Context) (*HttpRule, error) {
	nodes, err := hrq.Limit(2).All(setContextOp(ctx, hrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{httprule.Label}
	default:
		return nil, &NotSingularError{httprule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hrq *HttpRuleQuery) OnlyX(ctx context.Context) *HttpRule {
	node, err := hrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HttpRule ID in the query.
// Returns a *NotSingularError when more than one HttpRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (hrq *HttpRuleQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = hrq.Limit(2).IDs(setContextOp(ctx, hrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{httprule.Label}
	default:
		err = &NotSingularError{httprule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hrq *HttpRuleQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := hrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HttpRules.
func (hrq *HttpRuleQuery) All(ctx context.Context) ([]*HttpRule, error) {
	ctx = setContextOp(ctx, hrq.ctx, "All")
	if err := hrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HttpRule, *HttpRuleQuery]()
	return withInterceptors[[]*HttpRule](ctx, hrq, qr, hrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hrq *HttpRuleQuery) AllX(ctx context.Context) []*HttpRule {
	nodes, err := hrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HttpRule IDs.
func (hrq *HttpRuleQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if hrq.ctx.Unique == nil && hrq.path != nil {
		hrq.Unique(true)
	}
	ctx = setContextOp(ctx, hrq.ctx, "IDs")
	if err = hrq.Select(httprule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hrq *HttpRuleQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := hrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hrq *HttpRuleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hrq.ctx, "Count")
	if err := hrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hrq, querierCount[*HttpRuleQuery](), hrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hrq *HttpRuleQuery) CountX(ctx context.Context) int {
	count, err := hrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hrq *HttpRuleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hrq.ctx, "Exist")
	switch _, err := hrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hrq *HttpRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := hrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HttpRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hrq *HttpRuleQuery) Clone() *HttpRuleQuery {
	if hrq == nil {
		return nil
	}
	return &HttpRuleQuery{
		config:     hrq.config,
		ctx:        hrq.ctx.Clone(),
		order:      append([]httprule.OrderOption{}, hrq.order...),
		inters:     append([]Interceptor{}, hrq.inters...),
		predicates: append([]predicate.HttpRule{}, hrq.predicates...),
		// clone intermediate query.
		sql:  hrq.sql.Clone(),
		path: hrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GwURL string `json:"gw_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HttpRule.Query().
//		GroupBy(httprule.FieldGwURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hrq *HttpRuleQuery) GroupBy(field string, fields ...string) *HttpRuleGroupBy {
	hrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HttpRuleGroupBy{build: hrq}
	grbuild.flds = &hrq.ctx.Fields
	grbuild.label = httprule.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GwURL string `json:"gw_url,omitempty"`
//	}
//
//	client.HttpRule.Query().
//		Select(httprule.FieldGwURL).
//		Scan(ctx, &v)
func (hrq *HttpRuleQuery) Select(fields ...string) *HttpRuleSelect {
	hrq.ctx.Fields = append(hrq.ctx.Fields, fields...)
	sbuild := &HttpRuleSelect{HttpRuleQuery: hrq}
	sbuild.label = httprule.Label
	sbuild.flds, sbuild.scan = &hrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HttpRuleSelect configured with the given aggregations.
func (hrq *HttpRuleQuery) Aggregate(fns ...AggregateFunc) *HttpRuleSelect {
	return hrq.Select().Aggregate(fns...)
}

func (hrq *HttpRuleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hrq); err != nil {
				return err
			}
		}
	}
	for _, f := range hrq.ctx.Fields {
		if !httprule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hrq.path != nil {
		prev, err := hrq.path(ctx)
		if err != nil {
			return err
		}
		hrq.sql = prev
	}
	return nil
}

func (hrq *HttpRuleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HttpRule, error) {
	var (
		nodes = []*HttpRule{}
		_spec = hrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HttpRule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HttpRule{config: hrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (hrq *HttpRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hrq.querySpec()
	_spec.Node.Columns = hrq.ctx.Fields
	if len(hrq.ctx.Fields) > 0 {
		_spec.Unique = hrq.ctx.Unique != nil && *hrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hrq.driver, _spec)
}

func (hrq *HttpRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(httprule.Table, httprule.Columns, sqlgraph.NewFieldSpec(httprule.FieldID, field.TypeUint32))
	_spec.From = hrq.sql
	if unique := hrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hrq.path != nil {
		_spec.Unique = true
	}
	if fields := hrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, httprule.FieldID)
		for i := range fields {
			if fields[i] != httprule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hrq *HttpRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hrq.driver.Dialect())
	t1 := builder.Table(httprule.Table)
	columns := hrq.ctx.Fields
	if len(columns) == 0 {
		columns = httprule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hrq.sql != nil {
		selector = hrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hrq.ctx.Unique != nil && *hrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hrq.predicates {
		p(selector)
	}
	for _, p := range hrq.order {
		p(selector)
	}
	if offset := hrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HttpRuleGroupBy is the group-by builder for HttpRule entities.
type HttpRuleGroupBy struct {
	selector
	build *HttpRuleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hrgb *HttpRuleGroupBy) Aggregate(fns ...AggregateFunc) *HttpRuleGroupBy {
	hrgb.fns = append(hrgb.fns, fns...)
	return hrgb
}

// Scan applies the selector query and scans the result into the given value.
func (hrgb *HttpRuleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hrgb.build.ctx, "GroupBy")
	if err := hrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HttpRuleQuery, *HttpRuleGroupBy](ctx, hrgb.build, hrgb, hrgb.build.inters, v)
}

func (hrgb *HttpRuleGroupBy) sqlScan(ctx context.Context, root *HttpRuleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hrgb.fns))
	for _, fn := range hrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hrgb.flds)+len(hrgb.fns))
		for _, f := range *hrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HttpRuleSelect is the builder for selecting fields of HttpRule entities.
type HttpRuleSelect struct {
	*HttpRuleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hrs *HttpRuleSelect) Aggregate(fns ...AggregateFunc) *HttpRuleSelect {
	hrs.fns = append(hrs.fns, fns...)
	return hrs
}

// Scan applies the selector query and scans the result into the given value.
func (hrs *HttpRuleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hrs.ctx, "Select")
	if err := hrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HttpRuleQuery, *HttpRuleSelect](ctx, hrs.HttpRuleQuery, hrs, hrs.inters, v)
}

func (hrs *HttpRuleSelect) sqlScan(ctx context.Context, root *HttpRuleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hrs.fns))
	for _, fn := range hrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
